
services:
  mongo:
    image: mongo
    restart: always
    env_file:
      - .env
    ports:
      - ${MONGO_PORT}:27017

  mongo-express: 
    image: mongo-express
    restart: always
    env_file:
      - .env
    ports:
      - ${ME_PORT}:8081
    environment:
      ME_CONFIG_BASICAUTH: false

  redis:
    image: redis
    env_file:
      - .env
    ports:
      - ${REDIS_PORT}:6379
    volumes:
      - redis:/data
  
  redis-commander:
    image: rediscommander/redis-commander
    restart: always
    env_file:
      - .env
    ports:
      - "${RC_PORT}:8081"
    environment:
      - REDIS_HOST=redis

  rabbitmq:
    image: rabbitmq:3-management
    restart: always
    env_file:
        - .env
    ports:
      - ${RMQ_PORT}:5672
      - ${RMQ_MANAGEMENT_PORT}:15672
    volumes:
      - rabbitmq-lib:/var/lib/rabbitmq
      - rabbitmq-log:/var/log/rabbitmq



volumes:
  redis:
    driver: local
  rabbitmq-lib:
    driver: local
  rabbitmq-log:
    driver: local
