
services:
  mongo:
    image: mongo
    restart: always
    environment: 
      MONGO_INITDB_ROOT_USERNAME: teste
      MONGO_INITDB_ROOT_PASSWORD: teste

  mongo-express: 
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: teste
      ME_CONFIG_MONGODB_ADMINPASSWORD: teste
      ME_CONFIG_MONGODB_URL: mongodb://teste:teste@mongo:27017/
      ME_CONFIG_BASICAUTH: false

  redis:
    image: redis
    ports: 
      - 6379:6379
    volumes:
      - redis:/data
  
  redis-commander:
    image: rediscommander/redis-commander
    restart: always
    ports:
      - "8082:8081"
    environment:
      - REDIS_HOST= redis
    



volumes:
  redis:
    driver: local
